name: K6 Load Test

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: k6 Load Test
        id: k6
        uses: grafana/k6-action@v0.3.1
        with:
          cloud: true
          token: ${{ secrets.K6_CLOUD_TOKEN }}
          filename: my_k6_project/scripts/k6io.js

      - name: Download k6 results
        run: |
          curl -L -o k6results.json "${{ steps.k6.outputs.resultURL }}"

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
            name: k6-results
            path: k6results.json
