name: K6 performance test

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.3

      - name: Install K6
        run: |
          go install go.k6.io/k6/cmd/xk6@latest

      - name: Run K6 test
        run: |
          $GOPATH/bin/k6 run --out json=results/k6io.json scripts/k6io.js

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
          name: k6-results
          path: results/k6io.json
