name: K6 docker performance test

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -R

      - name: Run K6 test
        run: |
          docker run -v $PWD:/src -i grafana/k6 run --out json=k6io.json /src/my_k6_project/scripts/k6io.js
          ls
          cat k6io.json

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
            name: k6-results
            path: k6io.json
