name: K6 docker performance test

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Run K6 test
        uses: docker://grafana/k6:latest
        with:
          args: run --out json=k6io.json scripts/k6io.js

      - name: Print JSON results
        run: cat k6io.json

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
            name: k6-results
            path: k6io.json
