name: K6 performance test

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.3

      - name: Set up k6
        run: |
          curl -sL https://github.com/grafana/k6/releases/download/v0.50.0/k6-v0.50.0-linux-amd64.tar.gz | tar -xz
          sudo mv k6-v0.50.0-linux-amd64/k6 /usr/bin/k6

      - name: Run K6 test
        run: |
          pwd
          ls
          cd my_k6_project
          $GOPATH/bin/k6 run --out json=k6io.json scripts/k6io.js
          pwd
          ls

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
            name: k6-results
            path: ${{ github.workspace }}/my_k6_project/k6io.json
