name: K6 docker performance test

on: 
  push:
  workflow_dispatch:
  
jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Run K6 test
        run: |
          docker run --rm --user $(id -u):$(id -g) -v $PWD:/src -i grafana/k6 run /src/my_k6_project/scripts/k6io.js --out json=/src/my_k6_project/k6io.json
          ls
          cat my_k6_project/k6io.json

      - name: Upload K6 results
        uses: actions/upload-artifact@v2
        with:
            name: k6-results
            path: my_k6_project/k6io.json
