# This is a basic workflow to help you get started with Actions

name: POC xk6

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build a new xk6 using the xk6-output-statsd extension
        run: |
          pwd
          ls
          chmod +x ./k6
          K6_STATSD_ENABLE_TAGS=true ./k6 run my_k6_project/scripts/k6io.js
